server:
  port: 9091

spring:
  application:
    name: email-provider-xtl
  cloud:
    stream:
      bindings:
        output: {destination: email-topic-xtl, tags: tagStr, content-type: application/json}
      rocketmq:
        binder:
          name-server: 120.25.207.44:9876
        bindings:
          output: {producer.tags: tagStr}
